apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-deleter-binding
  namespace: <namespace>  # Replace with the target namespace
subjects:
- kind: ServiceAccount
  name: cronjob-sa  # Replace with the CronJob's service account name
roleRef:
  kind: Role
  name: pod-deleter-role  # Name of the Role created in step 1
  apiGroup: rbac.authorization.k8s.io
